
# nome do nosso 'pipeline'
name: 'Execução Manual

on:
  schedule:
    - cron: '0 6 * * 0'

#Proximos passas sera as configuraçoes das açoes, trabalho/tarefas que ira ser executado na nossa pipeline
#trabalhos/tarefas dentro do pipeline = jobs

jobs:
  e2e-tests:

    #maquina que o job vai executar: Primeiro informar o comando 'runs-on = qual maquina o job ira rodar'
    runs-on: ubuntu-latest

    # passos do script de build:
    steps:
      # cline do projeto
      - uses: actions/checkout@v4

      # instalacao do node
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # instalacao do Yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      # instalancao das dependencias
      - name: Instalando dependencias
        run: yarn
      
      # instalacao do Playwright
      - name: Instalando Playwright
        run: yarn playwright install

      # executando os testes e2e
      - name: Executando Testes e2e
        run: yarn run e2e